model:
  type: transformer
  d_model: 256
  num_heads: 8
  num_blocks: 6
  seq_len: 256
  dropout: 0.1
  use_rope: False

tokenizer:
  type: bpe_hugging_face

training:
  batch_size: 128
  learning_rate: 3e-4
  weight_decay: 0.01
  max_iters: 10000
  eval_interval: 250
  eval_iters: 30
  warmup_iters: 300

data:
  train_size: 0.8
  val_size: 0.1
  test_size: 0.1
  file: letterboxd_filtered.jsonl
  seed: 42

