model:
  type: transformer
  d_model: 128
  num_heads: 6
  num_blocks: 4
  seq_len: 128
  dropout: 0.1
  use_rope: False

tokenizer:
  type: bpe_hugging_face

training:
  batch_size: 128
  learning_rate: 3e-4
  weight_decay: 0.01
  max_iters: 8000
  eval_interval: 250
  eval_iters: 30
  warmup_iters: 300

data:
  train_size: 0.8
  val_size: 0.1
  test_size: 0.1
  file: letterboxd_filtered_llm.jsonl
  level: 2
  seed: 42
